//
// Created by marco on 3/9/18.
//

#ifndef PROYECTOSUPERMERCADO_CAJAREGISTRADORA_H
#define PROYECTOSUPERMERCADO_CAJAREGISTRADORA_H


class CajaRegistradora {

};


#endif //PROYECTOSUPERMERCADO_CAJAREGISTRADORA_H
